# Generated by Django 4.0.4 on 2022-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='c_code',
            field=models.CharField(default='__', max_length=255),
        ),
    ]
